POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZFVzZXIiLCJpZCI6IjY5ODM1YTc5ZDExY2MyYjExZTg2OWNmMiIsImlhdCI6MTc3MDIxODIzNH0.g8jKg8q_XcnvTIRg4QUtk7nlGtvp45D2d8JT-pkvJWM

{
"title": "firstblog",
"author": "me",
"url": "firstentry",
"likes": 100
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZFVzZXIiLCJpZCI6IjY5ODM1YTc5ZDExY2MyYjExZTg2OWNmMiIsImlhdCI6MTc3MDIxODIzNH0.g8jKg8q_XcnvTIRg4QUtk7nlGtvp45D2d8JT-pkvJWM

{
"title": "secondblog",
"author": "notme",
"url": "secondentry",
"likes": 200
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
"title": "nolikes",
"author": "mr lonely",
"url": "emptyLikeMySoul"
}