POST http://localhost:3003/api/login
Content-Type: application/json

{
"username": "firstUser",
"password": "secretpassword"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
"username": "secondUser",
"password": "secretpassword2"
}