POST http://localhost:3001/api/persons
Content-Type: application/json

{
"name": "ab",
"number": "12"
}

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
"name": "forgotnumber"
}

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
"number": "123noname"
}